<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Pulumi.Automation" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\jd.core\jd.core.csproj" />
    <ProjectReference Include="..\..\src\backend-providers\jd.bp.pulumi\jd.bp.pulumi.csproj" />
  </ItemGroup>

</Project>
